local opts = { silent = true, noremap = true }

vim.keymap.set("n", "<leader>p", '"+p', opts)
vim.keymap.set("n", "<leader>P", '"+P', opts)
vim.keymap.set("n", "<leader>y", '"+y', opts)
vim.keymap.set("n", "<leader>Y", '"+Y', opts)
vim.keymap.set("n", "<leader>d", '"+d', opts)
vim.keymap.set("n", "<leader>D", '"+D', opts)
vim.keymap.set("v", "<leader>p", '"+p', opts)
vim.keymap.set("v", "<leader>P", '"+P', opts)
vim.keymap.set("v", "<leader>d", '"+d', opts)
vim.keymap.set("v", "<leader>D", '"+D', opts)
vim.keymap.set("v", "<leader>y", '"+y', opts)
vim.keymap.set("v", "<leader>Y", '"+Y', opts)
vim.keymap.set("n", "<Tab>", "<cmd>bn<cr>", opts)
vim.keymap.set("n", "<S-Tab>", "<cmd>bp<cr>", opts)
vim.keymap.set("v", "<", "<gv", opts)
vim.keymap.set("v", ">", ">gv", opts)
vim.keymap.set("n", "0", "^", opts)
vim.keymap.set("n", "^", "0", opts)
vim.keymap.set("n", "<up>", "<nop>", opts)
vim.keymap.set("n", "<down>", "<nop>", opts)
vim.keymap.set("n", "<left>", "<nop>", opts)
vim.keymap.set("n", "<right>", "<nop>", opts)
